// Auto-generated by deploy.ts — do not edit manually
// Network: sepolia | ChainId: 11155111
// Deployed: 2026-03-26T08:34:24.341Z

export const CONTRACT_ADDRESSES = {
  FreelanceEscrow: "0xa5E2Ce321Ff8b66eb748Fd7fadA6C4B3F73219B0",
  Reputation: "0x56fBcD1716271c7257fB703548f6Afd58CB6412F",
} as const;
