// Auto-generated by deploy.ts
export const CONTRACT_ADDRESSES = {
  FreelanceEscrow: "0xff4aB77d00b9834F8973c0581E48404a1e6cB412",
  Reputation:      "0xC032356808a2731954C2ef28fAeF3e4f1c42234e",
} as const;
