// Auto-generated by deploy.ts
export const CONTRACT_ADDRESSES = {
  JudgeRegistry:   "0xfF968C32D86CF785B9EF0B1FC80C6aFFD46DC38F",
  FreelanceEscrow: "0x35A81eaA4724c26dccEd4008AC1340E77248C998",
  Reputation:      "0x4AC4188758D32A800aCE16Fe8CE028E2b30C80B1",
} as const;
